#=======================================================================================#
# Objectif : Fichier definissant les applications de chaque conteneur 
# Nom : Quentin Capaccioli
# Date : 23/06/2026
# Derniere modification: Creation docker compose
#=======================================================================================#

services:

  # ── Conteneur 1 : py_robot_core + py_dashboard_cli ────────────────────
  roomba:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: roomba
    network_mode: host
    volumes:
      - ./config:/config
      - ./launch:/VirtualRoomba/install/virtual_roomba/share/virtual_roomba